#+title: The Emacs HELP you never knew you needed
#+OPTIONS: \n:t
#+STARTUP: showall
#+DATE: Created on 24 May 2023 @06:24

The Emacs HELP you never knew you needed.

The best way to go about looking for help (in the following order):

*MAIN HELP COMMAND: C-h C-h*

Main navigating keys:

q - quit
Page-Up - scroll forward only
Page-Down - scroll backwards only
SPC - scroll forward, but also jump to next section when scrolling is finished
Backspace - scroll backwards but also jump to next section
TAB -- to transverse hyperlinks, forwards
SHIFT-TAB -- backwards
RET -- to open a hyperlink
(In this case, RET means ~push-button~ rather than return or enter.)
l -- to go back to where you were before ~Info-history-back~
< -- Go to the beginning of the buffer.
> -- Go to the end of the buffer.

*apropos-command* -- C-h a

Used to find Emacs commands (interactive functions) by keyword.

e.g. version

tab cycles entries

The term apropos means "with relation to" or "relevant to" the given search term.

*Emacs Manual Index* -- C-h r i

~r~ tells Emacs to open the Emacs manual

Quickly find information in the Emacs manual.

e.g. macros

*FAQ* -- C-h C-f

*C-h f* -- describes a function

~isearch-forward-regexp~
~query-replace-regexp~
~replace-regexp~
~re-builder~

*C-h k* -- Let's you see what command is bound to a specific key (if any)

*C-h w* -- See what keybinding a specific command has (if any)

Here you enter the name of the command, rather than the keys.

e.g. ~emacs-version~

*C-h e* -- Displays the contents of the Messages Buffer

This is helpful for troubleshooting, for example if a command did not work as expected and you want to check if Emacs gave any error messages. It's also useful for looking up information that was displayed in the echo area but that disappeared before you could make note of it.

*C-h C-h b* or *C-h b* -- show all key bindings

*C-h m* -- Describe active (enabled) modes in current buffer

Helpful for finding important keybindings for that mode.

*C-h n* -- See latest Emacs news

*Any prefix key + C-h* -- To view a list of commands beginning with that prefix key

-------------------------------------------------------------------
More help..

C-h p -- Browse BUILT-IN packages by category or keyword. When you install Emacs, it comes with a large number of built-in packages or libraries that extend its functionality. You can discover these by keywords, i.e. categories.
